version: 1.0
runtime: nodejs22
build:
  commands:
    build:
      - npm install
run:
  command: node app.js
  network:
    port: 3000
    env: PORT
  secrets:
    - name: DB_HOST
      value-from: "arn:aws:secretsmanager:ap-northeast-1:559784498787:secret:SECRET_NAME:host::"
    - name: DB_PORT
      value-from: "arn:aws:secretsmanager:ap-northeast-1:559784498787:secret:SECRET_NAME:port::"
    - name: DB_USER
      value-from: "arn:aws:secretsmanager:ap-northeast-1:559784498787:secret:SECRET_NAME:username::"
    - name: DB_PASSWORD
      value-from: "arn:aws:secretsmanager:ap-northeast-1:559784498787:secret:SECRET_NAME:password::"
    - name: DB_NAME
      value-from: "arn:aws:secretsmanager:ap-northeast-1:559784498787:secret:SECRET_NAME:dbname::"
